-- =============================================================================
-- Файл: checkers_schema_full.sql
-- Описание: Единый скрипт для создания полной схемы БД проекта "Шашки на Oracle".
-- Версия: 1.1 (с исправленной таблицей audit_log)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- I. ОЧИСТКА СУЩЕСТВУЮЩИХ ОБЪЕКТОВ
-- -----------------------------------------------------------------------------
BEGIN
    FOR i IN (SELECT 'DROP TABLE ' || table_name || ' CASCADE CONSTRAINTS PURGE' AS stmt FROM user_tables
              WHERE table_name IN (
                'PLAYERS', 'GAME_RULES', 'SEASONS', 'PLAYER_RATINGS', 'MATCHES', 'GAMES',
                'GAME_MOVES', 'PUZZLES', 'DAILY_PUZZLES', 'PUZZLE_ATTEMPTS', 'AUDIT_LOG'
              )) LOOP
        EXECUTE IMMEDIATE i.stmt;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- =============================================================================
-- II. СОЗДАНИЕ ТАБЛИЦ
-- =============================================================================

-- 1. PLAYERS
CREATE TABLE players (
    player_id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR2(128) NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    last_activity_at  TIMESTAMP WITH TIME ZONE, -- << НОВОЕ ПОЛЕ
    CONSTRAINT pk_players PRIMARY KEY (player_id),
    CONSTRAINT uk_players_username UNIQUE (username)
);

-- 2. GAME_RULES
CREATE TABLE game_rules (
    rule_id                     INT NOT NULL,
    rule_name                   VARCHAR2(50) NOT NULL,
    board_size                  INT DEFAULT 8 NOT NULL,
    rule_description            VARCHAR2(1000),
    CONSTRAINT pk_game_rules PRIMARY KEY (rule_id),
    CONSTRAINT uk_game_rules_name UNIQUE (rule_name)
);

-- 3. SEASONS
CREATE TABLE seasons (
    season_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    season_name VARCHAR2(128) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    is_active   CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_seasons PRIMARY KEY (season_id),
    CONSTRAINT chk_seasons_active CHECK (is_active IN ('Y', 'N'))
);
COMMENT ON TABLE seasons IS 'Рейтинговые сезоны.';

-- 4. PLAYER_RATINGS
CREATE TABLE player_ratings (
    player_rating_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id        INT NOT NULL,
    rule_id          INT NOT NULL,
    season_id        INT NOT NULL,
    rating           INT DEFAULT 500 NOT NULL,
    matches_played   INT DEFAULT 0 NOT NULL,
    wins             INT DEFAULT 0 NOT NULL,
    losses           INT DEFAULT 0 NOT NULL,
    draws            INT DEFAULT 0 NOT NULL,
    CONSTRAINT pk_player_ratings PRIMARY KEY (player_rating_id),
    CONSTRAINT fk_ratings_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_ratings_season FOREIGN KEY (season_id) REFERENCES seasons(season_id)
);
COMMENT ON TABLE player_ratings IS 'Рейтинги и статистика игроков в разрезе правил и сезонов.';

-- 5. MATCHES
CREATE TABLE matches (
    match_id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id            INT NOT NULL,
    player1_id         INT NOT NULL,
    player2_id         INT NOT NULL,
    games_to_win       INT NOT NULL,
    player1_score      INT DEFAULT 0 NOT NULL,
    player2_score      INT DEFAULT 0 NOT NULL,
    status             CHAR(1) DEFAULT 'S' NOT NULL, -- S: Scheduled, A: Active, C: Completed
    winner_player_id   INT,
    start_time         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_matches PRIMARY KEY (match_id),
    CONSTRAINT fk_matches_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_matches_player1 FOREIGN KEY (player1_id) REFERENCES players(player_id),
    CONSTRAINT fk_matches_player2 FOREIGN KEY (player2_id) REFERENCES players(player_id),
    CONSTRAINT fk_matches_winner FOREIGN KEY (winner_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_matches_status CHECK (status IN ('S', 'A', 'C'))
);
COMMENT ON TABLE matches IS 'Серии игр (матчи), состоящие из нескольких партий.';

-- 6. GAMES
CREATE TABLE games (
    game_id                   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id                  INT,
    rule_id                   INT DEFAULT 1 NOT NULL,
    creator_player_id         INT NOT NULL,
    player_white_id           INT,
    player_black_id           INT,
    status                    CHAR(1) NOT NULL, -- O:Open, C:Challenged, A:Active, V:Victory, D:Draw, T:Timeout, R:Resigned
    current_turn              CHAR(1) DEFAULT 'W' NOT NULL,
    board_position            VARCHAR2(100) NOT NULL,
    moves_since_capture       INT DEFAULT 0 NOT NULL,
    last_move_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    winner_player_id          INT,
    start_time                TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time                  TIMESTAMP WITH TIME ZONE,
    time_limit_move_sec       INT,
    time_limit_game_sec       INT,
    ai_difficulty             CHAR(1),
    draw_offered_by           INT,
    draw_offer_status         CHAR(1), -- O:Offered, S:Seen, D:Declined
    draw_offered_at           TIMESTAMP WITH TIME ZONE,
    enable_pos_repetition_draw CHAR(1) DEFAULT 'N' NOT NULL,
    draw_moves_limit          INT,
    CONSTRAINT pk_games PRIMARY KEY (game_id),
    CONSTRAINT fk_games_match FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_games_creator FOREIGN KEY (creator_player_id) REFERENCES players(player_id),
    CONSTRAINT fk_games_player_white FOREIGN KEY (player_white_id) REFERENCES players(player_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_player_black FOREIGN KEY (player_black_id) REFERENCES players(player_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_winner FOREIGN KEY (winner_player_id) REFERENCES players(player_id),
    CONSTRAINT fk_games_draw_offered_by FOREIGN KEY (draw_offered_by) REFERENCES players(player_id),

    CONSTRAINT chk_games_status CHECK (status IN ('O', 'C', 'A', 'V', 'D', 'T', 'R')),
    CONSTRAINT chk_games_turn CHECK (current_turn IN ('W', 'B')),
    CONSTRAINT chk_ai_difficulty CHECK (ai_difficulty IN ('E', 'M', 'H') OR ai_difficulty IS NULL),
    
    CONSTRAINT chk_games_draw_status CHECK (draw_offer_status IN ('O', 'S', 'D')),
    CONSTRAINT chk_games_draw_offer_logic CHECK (
        (draw_offer_status IS NULL AND draw_offered_by IS NULL AND draw_offered_at IS NULL) OR
        (draw_offer_status IS NOT NULL AND draw_offered_by IS NOT NULL AND draw_offered_at IS NOT NULL)
    ),
    CONSTRAINT chk_game_rules_pos_rep CHECK (enable_pos_repetition_draw IN ('Y', 'N')),
    CONSTRAINT chk_game_draw_moves_limit CHECK (draw_moves_limit IS NULL OR draw_moves_limit > 0)
);

COMMENT ON TABLE games IS 'Игровые партии и их текущее состояние.';

-- 7. GAME_MOVES
CREATE TABLE game_moves (
    move_id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id         INT NOT NULL,
    move_number     INT NOT NULL,
    player_id       INT,
    move_notation   VARCHAR2(50) NOT NULL,
    is_capture      CHAR(1) DEFAULT 'N' NOT NULL,
    move_timestamp  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    board_position  VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_game_moves PRIMARY KEY (move_id),
    CONSTRAINT fk_game_moves_game FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE,
    CONSTRAINT fk_game_moves_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT chk_game_moves_capture CHECK (is_capture IN ('Y', 'N'))
);
COMMENT ON TABLE game_moves IS 'Протокол ходов всех партий.';

-- 8. PUZZLES
CREATE TABLE puzzles (
    puzzle_id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    board_position       VARCHAR2(100) NOT NULL,
    turn_to_move         CHAR(1) DEFAULT 'W' NOT NULL,
    moves_to_solve       INT DEFAULT NULL,
    difficulty_level     CHAR(1) DEFAULT 1 NOT NULL,
    created_by_player_id INT,
    CONSTRAINT pk_puzzles PRIMARY KEY (puzzle_id),
    CONSTRAINT fk_puzzles_player FOREIGN KEY (created_by_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_puzzles_turn CHECK (turn_to_move IN ('W', 'B'))
);
COMMENT ON TABLE puzzles IS 'Хранилище для режима "задачник".';

-- 9. DAILY_PUZZLES
CREATE TABLE daily_puzzles (
    daily_puzzle_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    puzzle_date DATE NOT NULL,
    puzzle_id   INT NOT NULL,
    CONSTRAINT pk_daily_puzzles PRIMARY KEY (daily_puzzle_id),
    CONSTRAINT fk_daily_puzzles_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(puzzle_id)
);
COMMENT ON TABLE daily_puzzles IS 'Связывает задачу из таблицы puzzles с конкретной датой.';

-- 10. PUZZLE_ATTEMPTS
CREATE TABLE puzzle_attempts (
    attempt_id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    puzzle_id       INT NOT NULL,
    player_id       INT NOT NULL,
    status          CHAR(1) NOT NULL, -- P: In Progress, S: Solved F: Failed
    start_time      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time        TIMESTAMP WITH TIME ZONE,
    move_number     INT NOT NULL,
    board_position  VARCHAR2(100) NOT NULL,
    is_daily        CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_puzzle_attempts PRIMARY KEY (attempt_id),
    CONSTRAINT fk_puzzle_attempts_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(puzzle_id) ON DELETE CASCADE,
    CONSTRAINT fk_puzzle_attempts_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
    CONSTRAINT chk_puzzle_attempts_status CHECK (status IN ('P', 'S', 'F')) -- P: In Progress, S: Solved F: Failed
);
COMMENT ON TABLE puzzle_attempts IS 'Результаты решения задач игроками.';

-- 11. AUDIT_LOG
CREATE TABLE audit_log (
    log_id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_timestamp   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    player_id       INT,
    game_id         INT,
    event_type      VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (log_id),
    CONSTRAINT fk_audit_log_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE SET NULL
);
COMMENT ON TABLE audit_log IS 'Журнал аудита для значимых событий и ошибок.';

-- =============================================================================
-- III. ИНДЕКСЫ
-- =============================================================================
CREATE INDEX idx_games_status ON games(status);
CREATE INDEX idx_games_players ON games(player_white_id, player_black_id);
CREATE INDEX idx_game_moves_game_id ON game_moves(game_id);
CREATE INDEX idx_player_ratings_main ON player_ratings(season_id, rule_id, rating DESC);
CREATE INDEX idx_puzzle_attempts_player ON puzzle_attempts(player_id);

-- =============================================================================
-- IV. НАЧАЛЬНЫЕ ДАННЫЕ
-- =============================================================================
INSERT INTO game_rules (rule_id, rule_name, board_size,rule_description)
VALUES (1, 'Русские шашки 8x8', 8, 'Blah blah blah Russan checkers rules description.');
INSERT INTO game_rules (rule_id, rule_name, board_size, rule_description)
VALUES (2, 'Международные шашки 10x10', 10, 'Blah blah blah International checkers rules description.');


-- Run this block once to set up the puzzles
BEGIN
    -- Clear existing puzzle data to avoid duplicates
    DELETE FROM C##CHECKERS_APP.puzzle_attempts;
    DELETE FROM C##CHECKERS_APP.daily_puzzles;
    DELETE FROM C##CHECKERS_APP.puzzles WHERE created_by_player_id IS NULL;
    
    -- Difficulty 0 (Easy)
    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('12b4b5b2b8w1b1w11w3w8', 'W', 4, 0, NULL);

    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('10b1b6b1b8b4w3w13w1b2w5', 'W', 3, 0, NULL);

    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('12b4b3b8b4w1b1w2w8w12', 'W', 3, 0, NULL);

    -- Difficulty 1 (Medium)
    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('1b12b6b3b2b4b1w1b1w6w4w3b2w1w1w1', 'W', 9, 1, NULL);

    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('17b1b13w1b3b4b8w1ww3w3', 'W', 5, 1, NULL);

    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('14b2b1b1b6b4w6w1w1w15w3', 'W', 6, 1, NULL);

    -- Difficulty 2 (Hard)
    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('5b1bb12w2w12b17b4w1w1', 'W', 12, 2, NULL);

    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('8w1b13b3b6b6w1b13w1w3', 'W', 5, 2, NULL);

    INSERT INTO C##CHECKERS_APP.puzzles (board_position, turn_to_move, moves_to_solve, difficulty_level, created_by_player_id)
    VALUES ('8w1b1b1w18w1b4b10w3b8', 'W', 4, 2, NULL);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('[OK] 9 predefined puzzles have been inserted.');
END;




-----DAILY PUZZLE JOB SETUP-----
        DECLARE
            v_puzzle_id puzzles.puzzle_id%TYPE;
            v_today     DATE := TRUNC(SYSDATE);
            v_count     PLS_INTEGER;
        BEGIN
            -- Check if a puzzle for today already exists
            SELECT COUNT(*) INTO v_count FROM daily_puzzles WHERE puzzle_date = v_today;

            IF v_count = 0 THEN
                -- Select a random server-created puzzle that wasn't used recently (e.g., last 30 days)
                SELECT puzzle_id INTO v_puzzle_id
                FROM (
                    SELECT p.puzzle_id
                    FROM puzzles p
                    LEFT JOIN daily_puzzles dp ON p.puzzle_id = dp.puzzle_id AND dp.puzzle_date >= v_today
                    WHERE p.created_by_player_id IS NULL -- Only server puzzles
                    AND dp.puzzle_id IS NULL -- Not used recently
                    ORDER BY DBMS_RANDOM.VALUE
                ) WHERE ROWNUM = 1;

                -- Assign it for today
                INSERT INTO daily_puzzles (puzzle_date, puzzle_id) VALUES (v_today, v_puzzle_id);
                COMMIT;
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                -- Handle case where no suitable puzzle is found (e.g., log an error)
                NULL; -- Or raise an error, or pick any puzzle
        END;


BEGIN
  DBMS_SCHEDULER.CREATE_JOB (
    job_name        => 'DAILY_CHECKERS_PUZZLE_JOB',
    job_type        => 'PLSQL_BLOCK',
    job_action      => q'[
        DECLARE
            v_puzzle_id puzzles.puzzle_id%TYPE;
            v_today     DATE := TRUNC(SYSDATE);
            v_count     PLS_INTEGER;
        BEGIN
            -- Check if a puzzle for today already exists
            SELECT COUNT(*) INTO v_count FROM daily_puzzles WHERE puzzle_date = v_today;

            IF v_count = 0 THEN
                -- Select a random server-created puzzle that wasn't used recently (e.g., last 30 days)
                SELECT puzzle_id INTO v_puzzle_id
                FROM (
                    SELECT p.puzzle_id
                    FROM puzzles p
                    LEFT JOIN daily_puzzles dp ON p.puzzle_id = dp.puzzle_id AND dp.puzzle_date >= v_today
                    WHERE p.created_by_player_id IS NULL -- Only server puzzles
                    AND dp.puzzle_id IS NULL -- Not used recently
                    ORDER BY DBMS_RANDOM.VALUE
                ) WHERE ROWNUM = 1;

                -- Assign it for today
                INSERT INTO daily_puzzles (puzzle_date, puzzle_id) VALUES (v_today, v_puzzle_id);
                COMMIT;
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                -- Handle case where no suitable puzzle is found (e.g., log an error)
                NULL; -- Or raise an error, or pick any puzzle
        END;
    ]',
    start_date      => TRUNC(SYSTIMESTAMP) + INTERVAL '1' HOUR, -- Start tomorrow at 1 AM
    repeat_interval => 'FREQ=DAILY; BYHOUR=1; BYMINUTE=0; BYSECOND=0', -- Run daily at 1 AM
    enabled         => TRUE,
    comments        => 'Selects a random checkers puzzle for the daily challenge.');
END;

--SELECT * FROM USER_SCHEDULER_JOBS
--SELECT * FROM DAILY_PUZZLES
--SELECT * FROM PUZZLES
-- =============================================================================
-- V. ЗАВЕРШЕНИЕ ТРАНЗАКЦИИ
-- =============================================================================
COMMIT;