-- =============================================================================
-- Файл: checkers_schema_full.sql
-- Описание: Единый скрипт для создания полной схемы БД проекта "Шашки на Oracle".
-- Версия: 1.1 (с исправленной таблицей audit_log)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- I. ОЧИСТКА СУЩЕСТВУЮЩИХ ОБЪЕКТОВ
-- -----------------------------------------------------------------------------
BEGIN
    FOR i IN (SELECT 'DROP TABLE ' || table_name || ' CASCADE CONSTRAINTS PURGE' AS stmt FROM user_tables
              WHERE table_name IN (
                'PLAYERS', 'GAME_RULES', 'SEASONS', 'PLAYER_RATINGS', 'MATCHES', 'GAMES',
                'GAME_MOVES', 'PUZZLES', 'DAILY_PUZZLES', 'PUZZLE_ATTEMPTS', 'AUDIT_LOG'
              )) LOOP
        EXECUTE IMMEDIATE i.stmt;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- =============================================================================
-- II. СОЗДАНИЕ ТАБЛИЦ
-- =============================================================================

-- 1. PLAYERS
CREATE TABLE players (
    player_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR2(128) NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    last_activity_at  TIMESTAMP WITH TIME ZONE, -- << НОВОЕ ПОЛЕ
    CONSTRAINT pk_players PRIMARY KEY (player_id),
    CONSTRAINT uk_players_username UNIQUE (username)
);

-- 2. GAME_RULES
CREATE TABLE game_rules (
    rule_id                     NUMBER(3) NOT NULL,
    rule_name                   VARCHAR2(50) NOT NULL,
    board_size                  NUMBER(2) DEFAULT 8 NOT NULL,
    draw_moves_limit            NUMBER(3) DEFAULT 40 NOT NULL,
    enable_pos_repetition_draw  CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_game_rules PRIMARY KEY (rule_id),
    CONSTRAINT uk_game_rules_name UNIQUE (rule_name),
    CONSTRAINT chk_game_rules_pos_rep CHECK (enable_pos_repetition_draw IN ('Y', 'N'))
);
COMMENT ON TABLE game_rules IS 'Справочник правил игры (русские, международные и т.д.).';

-- 3. SEASONS
CREATE TABLE seasons (
    season_id   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    season_name VARCHAR2(100) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    is_active   CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_seasons PRIMARY KEY (season_id),
    CONSTRAINT chk_seasons_active CHECK (is_active IN ('Y', 'N'))
);
COMMENT ON TABLE seasons IS 'Рейтинговые сезоны.';

-- 4. PLAYER_RATINGS
CREATE TABLE player_ratings (
    player_id       NUMBER(10) NOT NULL,
    rule_id         NUMBER(3) NOT NULL,
    season_id       NUMBER(5) NOT NULL,
    rating          NUMBER(6, 2) DEFAULT 1500.00 NOT NULL,
    matches_played  NUMBER(5) DEFAULT 0 NOT NULL,
    wins            NUMBER(5) DEFAULT 0 NOT NULL,
    losses          NUMBER(5) DEFAULT 0 NOT NULL,
    draws           NUMBER(5) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_player_ratings PRIMARY KEY (player_id, rule_id, season_id),
    CONSTRAINT fk_ratings_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_ratings_season FOREIGN KEY (season_id) REFERENCES seasons(season_id)
);
COMMENT ON TABLE player_ratings IS 'Рейтинги и статистика игроков в разрезе правил и сезонов.';

-- 5. MATCHES
CREATE TABLE matches (
    match_id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id            NUMBER(3) NOT NULL,
    player1_id         NUMBER(10) NOT NULL,
    player2_id         NUMBER(10) NOT NULL,
    games_to_win       NUMBER(2) NOT NULL,
    player1_score      NUMBER(2) DEFAULT 0 NOT NULL,
    player2_score      NUMBER(2) DEFAULT 0 NOT NULL,
    status             CHAR(1) DEFAULT 'S' NOT NULL, -- S: Scheduled, A: Active, C: Completed
    winner_player_id   NUMBER(10),
    start_time         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_matches PRIMARY KEY (match_id),
    CONSTRAINT fk_matches_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_matches_player1 FOREIGN KEY (player1_id) REFERENCES players(player_id),
    CONSTRAINT fk_matches_player2 FOREIGN KEY (player2_id) REFERENCES players(player_id),
    CONSTRAINT fk_matches_winner FOREIGN KEY (winner_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_matches_status CHECK (status IN ('S', 'A', 'C'))
);
COMMENT ON TABLE matches IS 'Серии игр (матчи), состоящие из нескольких партий.';

-- 6. GAMES
CREATE TABLE games (
    game_id             NUMBER(12) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id            NUMBER(10),
    rule_id             NUMBER(3) DEFAULT 1 NOT NULL,
    creator_player_id   NUMBER(10) NOT NULL,
    player_white_id     NUMBER(10),
    player_black_id     NUMBER(10),
    status              CHAR(1) NOT NULL, -- O:Open, C:Challenged, A:Active, V:Victory, D:Draw, T:Timeout
    current_turn        CHAR(1) DEFAULT 'W' NOT NULL,
    board_position      VARCHAR2(100) NOT NULL,
    moves_since_capture NUMBER(3) DEFAULT 0 NOT NULL,
    last_move_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    winner_player_id    NUMBER(10),
    start_time          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time            TIMESTAMP WITH TIME ZONE,
    time_limit_move_sec NUMBER(4),
    time_limit_game_sec NUMBER(5),
    ai_difficulty       NUMBER(1),
    is_resigned         CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (game_id),
    CONSTRAINT fk_games_match FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_games_creator FOREIGN KEY (creator_player_id) REFERENCES players(player_id),
    CONSTRAINT fk_games_player_white FOREIGN KEY (player_white_id) REFERENCES players(player_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_player_black FOREIGN KEY (player_black_id) REFERENCES players(player_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_winner FOREIGN KEY (winner_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_games_status CHECK (status IN ('O', 'C', 'A', 'V', 'D', 'T')),
    CONSTRAINT chk_games_turn CHECK (current_turn IN ('W', 'B')),
    CONSTRAINT chk_games_active_players CHECK (status <> 'A' OR (player_white_id IS NOT NULL AND player_black_id IS NOT NULL)),
    CONSTRAINT chk_ai_difficulty CHECK (ai_difficulty BETWEEN 0 AND 2)
);
COMMENT ON TABLE games IS 'Игровые партии и их текущее состояние.';

-- 7. GAME_MOVES
CREATE TABLE game_moves (
    move_id         NUMBER(18) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id         NUMBER(12) NOT NULL,
    move_number     NUMBER(4) NOT NULL,
    player_id       NUMBER(10) NOT NULL,
    move_notation   VARCHAR2(50) NOT NULL,
    is_capture      CHAR(1) DEFAULT 'N' NOT NULL,
    move_timestamp  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    board_position  VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_game_moves PRIMARY KEY (move_id),
    CONSTRAINT uk_game_moves_game_move UNIQUE (game_id, move_number),
    CONSTRAINT fk_game_moves_game FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE,
    CONSTRAINT fk_game_moves_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT chk_game_moves_capture CHECK (is_capture IN ('Y', 'N'))
);
COMMENT ON TABLE game_moves IS 'Протокол ходов всех партий.';

-- 8. PUZZLES
CREATE TABLE puzzles (
    puzzle_id            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    puzzle_name          VARCHAR2(100) NOT NULL,
    board_position       VARCHAR2(100) NOT NULL,
    turn_to_move         CHAR(1) DEFAULT 'W' NOT NULL,
    description          VARCHAR2(500),
    created_by_player_id NUMBER(10),
    CONSTRAINT pk_puzzles PRIMARY KEY (puzzle_id),
    CONSTRAINT fk_puzzles_player FOREIGN KEY (created_by_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_puzzles_turn CHECK (turn_to_move IN ('W', 'B'))
);
COMMENT ON TABLE puzzles IS 'Хранилище для режима "задачник".';

-- 9. DAILY_PUZZLES
CREATE TABLE daily_puzzles (
    daily_puzzle_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    puzzle_date DATE NOT NULL,
    puzzle_id   NUMBER(10) NOT NULL,
    CONSTRAINT pk_daily_puzzles PRIMARY KEY (daily_puzzle_id),
    CONSTRAINT fk_daily_puzzles_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(puzzle_id)
);
COMMENT ON TABLE daily_puzzles IS 'Связывает задачу из таблицы puzzles с конкретной датой.';

-- 10. PUZZLE_ATTEMPTS
CREATE TABLE puzzle_attempts (
    attempt_id      NUMBER(18) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    puzzle_id       NUMBER(10) NOT NULL,
    player_id       NUMBER(10) NOT NULL,
    status          CHAR(1) NOT NULL, -- P: In Progress, S: Solved
    start_time      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time        TIMESTAMP WITH TIME ZONE,
    moves_count     NUMBER(3),
    CONSTRAINT pk_puzzle_attempts PRIMARY KEY (attempt_id),
    CONSTRAINT fk_puzzle_attempts_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(puzzle_id) ON DELETE CASCADE,
    CONSTRAINT fk_puzzle_attempts_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
    CONSTRAINT chk_puzzle_attempts_status CHECK (status IN ('P', 'S')) -- P: In Progress, S: Solved
);
COMMENT ON TABLE puzzle_attempts IS 'Результаты решения задач игроками.';

-- 11. AUDIT_LOG
CREATE TABLE audit_log (
    log_id          NUMBER(18) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_timestamp   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    player_id       NUMBER(10),
    game_id         NUMBER(12),
    event_type      VARCHAR2(50) NOT NULL,
    event_details   VARCHAR2(1000),
    CONSTRAINT pk_audit_log PRIMARY KEY (log_id),
    CONSTRAINT fk_audit_log_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE SET NULL
);
COMMENT ON TABLE audit_log IS 'Журнал аудита для значимых событий и ошибок.';

-- =============================================================================
-- III. ИНДЕКСЫ
-- =============================================================================
CREATE INDEX idx_games_status ON games(status);
CREATE INDEX idx_games_players ON games(player_white_id, player_black_id);
CREATE INDEX idx_game_moves_game_id ON game_moves(game_id);
CREATE INDEX idx_player_ratings_main ON player_ratings(season_id, rule_id, rating DESC);
CREATE INDEX idx_puzzle_attempts_player ON puzzle_attempts(player_id);

-- =============================================================================
-- IV. НАЧАЛЬНЫЕ ДАННЫЕ
-- =============================================================================
INSERT INTO game_rules (rule_id, rule_name, board_size, draw_moves_limit, enable_pos_repetition_draw)
VALUES (1, 'Русские шашки 8x8', 8, 30, 'Y');
INSERT INTO game_rules (rule_id, rule_name, board_size, draw_moves_limit, enable_pos_repetition_draw)
VALUES (2, 'Международные шашки 10x10', 10, 50, 'Y');

INSERT INTO players (player_id, username, created_at, last_activity_at)
VALUES (0, USER, SYSTIMESTAMP, SYSTIMESTAMP); -- AI

-- =============================================================================
-- V. ЗАВЕРШЕНИЕ ТРАНЗАКЦИИ
-- =============================================================================
COMMIT;