-- =============================================================================
-- Файл: tables.sql
-- Описание: Скрипт для создания всех таблиц, последовательностей и индексов
--           для проекта "Шашки на Oracle".
-- =============================================================================

-- Чистка перед созданием (для удобства пересоздания схемы)
-- Drop Foreign Keys
ALTER TABLE game_moves DROP CONSTRAINT fk_game_moves_player;
ALTER TABLE game_moves DROP CONSTRAINT fk_game_moves_game;
ALTER TABLE games DROP CONSTRAINT fk_games_winner;
ALTER TABLE games DROP CONSTRAINT fk_games_player_black;
ALTER TABLE games DROP CONSTRAINT fk_games_player_white;
ALTER TABLE games DROP CONSTRAINT fk_games_rule;

-- Drop Check Constraints
ALTER TABLE game_rules DROP CONSTRAINT chk_game_rules_pos_rep;
ALTER TABLE game_moves DROP CONSTRAINT chk_game_moves_capture;
ALTER TABLE games DROP CONSTRAINT chk_games_turn;
ALTER TABLE games DROP CONSTRAINT chk_games_status;

-- Drop Unique Keys
ALTER TABLE game_moves DROP CONSTRAINT uk_game_moves_game_move;
ALTER TABLE game_rules DROP CONSTRAINT uk_game_rules_name;
ALTER TABLE players DROP CONSTRAINT uk_players_username;

-- Drop Primary Keys
ALTER TABLE audit_log DROP CONSTRAINT pk_audit_log;
ALTER TABLE game_moves DROP CONSTRAINT pk_game_moves;
ALTER TABLE games DROP CONSTRAINT pk_games;
ALTER TABLE game_rules DROP CONSTRAINT pk_game_rules;
ALTER TABLE players DROP CONSTRAINT pk_players;

BEGIN
    FOR i IN (SELECT table_name FROM user_tables WHERE table_name IN ('GAME_MOVES', 'GAMES', 'PLAYERS', 'GAME_RULES', 'AUDIT_LOG')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || i.table_name || ' PURGE';
    END LOOP;
END;
DROP table T_PLAYERS PURGE
/
SELECT table_name FROM user_tables WHERE table_name IN ('GAME_MOVES', 'GAMES', 'PLAYERS', 'GAME_RULES', 'AUDIT_LOG');
SELECT table_name FROM user_tables;
-- =============================================================================
-- 1. ТАБЛИЦЫ
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PLAYERS: Пользователи системы
-- Хранит информацию об игроках. Запись создается при первом участии в игре.
-- -----------------------------------------------------------------------------
CREATE TABLE players (
    player_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    username    VARCHAR2(128) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE players IS 'Игроки. Запись создается при создании первой партии пользователем БД.';
COMMENT ON COLUMN players.player_id IS 'Уникальный идентификатор игрока (PK).';
COMMENT ON COLUMN players.username IS 'Имя пользователя Oracle, уникально.';
COMMENT ON COLUMN players.created_at IS 'Дата и время регистрации игрока в системе.';


-- -----------------------------------------------------------------------------
-- GAME_RULES: Справочник правил игры
-- Позволяет в будущем легко добавлять новые варианты шашек (международные и т.д.)
-- -----------------------------------------------------------------------------
CREATE TABLE game_rules (
    rule_id             NUMBER(3) NOT NULL,
    rule_name           VARCHAR2(50) NOT NULL,
    board_size          NUMBER(2) DEFAULT 8 NOT NULL,
    draw_moves_limit    NUMBER(3) DEFAULT 40 NOT NULL, -- Лимит полуходов без взятия для ничьей
    enable_pos_repetition_draw CHAR(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON TABLE game_rules IS 'Справочник правил игры (русские, международные и т.д.).';
COMMENT ON COLUMN game_rules.rule_id IS 'Код правил (PK).';
COMMENT ON COLUMN game_rules.rule_name IS 'Наименование правил.';
COMMENT ON COLUMN game_rules.board_size IS 'Размер доски (8 для русских, 10 для международных).';
COMMENT ON COLUMN game_rules.draw_moves_limit IS 'Количество полуходов без взятий и движения дамок, после которого объявляется ничья.';
COMMENT ON COLUMN game_rules.enable_pos_repetition_draw IS 'Флаг (Y/N), включено ли правило ничьей по троекратному повторению позиции.';


-- -----------------------------------------------------------------------------
-- GAMES: Партии
-- Основная таблица, хранящая состояние текущих и результаты завершенных партий.
-- -----------------------------------------------------------------------------
CREATE TABLE games (
    game_id             NUMBER(12) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    rule_id             NUMBER(3) DEFAULT 1 NOT NULL, -- По умолчанию "Русские шашки"
    player_white_id     NUMBER(10) NOT NULL,
    player_black_id     NUMBER(10) NOT NULL,
    status              VARCHAR2(20) NOT NULL, -- ACTIVE, WHITE_WIN, BLACK_WIN, DRAW, TIMEOUT, ABORTED
    current_turn        CHAR(1) DEFAULT 'W' NOT NULL, -- 'W' - White, 'B' - Black
    board_position      VARCHAR2(64) NOT NULL, -- Строковое представление позиции на 32/50 игровых полях
    moves_since_capture NUMBER(3) DEFAULT 0 NOT NULL, -- Счетчик ходов без взятия для правила ничьей
    last_move_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    winner_player_id    NUMBER(10),
    start_time          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    end_time            TIMESTAMP WITH TIME ZONE,
    time_limit_move_sec NUMBER(4), -- Ограничение времени на ход в секундах
    time_limit_game_sec NUMBER(5)  -- Ограничение времени на всю партию в секундах
);

COMMENT ON TABLE games IS 'Игровые партии и их текущее состояние.';
COMMENT ON COLUMN games.game_id IS 'Уникальный идентификатор партии (PK).';
COMMENT ON COLUMN games.rule_id IS 'Правила, по которым идет игра (FK к game_rules).';
COMMENT ON COLUMN games.player_white_id IS 'ID игрока за белых (FK к players).';
COMMENT ON COLUMN games.player_black_id IS 'ID игрока за черных (FK к players).';
COMMENT ON COLUMN games.status IS 'Текущий статус партии.';
COMMENT ON COLUMN games.current_turn IS 'Чей сейчас ход (W/B).';
COMMENT ON COLUMN games.board_position IS 'Представление доски в виде строки. Для 8x8 - 32 символа, где каждый символ - состояние одного игрового поля (w,b,W,B,_).';
COMMENT ON COLUMN games.moves_since_capture IS 'Счетчик полуходов без взятия для определения ничьей.';
COMMENT ON COLUMN games.last_move_at IS 'Время последнего сделанного хода (для контроля таймаутов).';
COMMENT ON COLUMN games.winner_player_id IS 'ID победившего игрока, если партия завершена победой.';
COMMENT ON COLUMN games.start_time IS 'Время начала партии.';
COMMENT ON COLUMN games.end_time IS 'Время окончания партии.';
COMMENT ON COLUMN games.time_limit_move_sec IS 'Лимит на ход в секундах (параметр партии).';
COMMENT ON COLUMN games.time_limit_game_sec IS 'Лимит на партию в секундах (параметр партии).';


-- -----------------------------------------------------------------------------
-- GAME_MOVES: Протокол ходов партии
-- Хронологическая запись всех ходов в каждой партии.
-- -----------------------------------------------------------------------------
CREATE TABLE game_moves (
    move_id         NUMBER(18) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    game_id         NUMBER(12) NOT NULL,
    move_number     NUMBER(4) NOT NULL, -- Номер полухода
    player_id       NUMBER(10) NOT NULL,
    move_notation   VARCHAR2(50) NOT NULL, -- Алгебраическая нотация хода (e.g., "c3-d4", "a3:c5:e7")
    is_capture      CHAR(1) DEFAULT 'N' NOT NULL,
    move_timestamp  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE game_moves IS 'Протокол ходов всех партий.';
COMMENT ON COLUMN game_moves.move_id IS 'Уникальный ID хода (PK).';
COMMENT ON COLUMN game_moves.game_id IS 'ID партии, к которой относится ход (FK к games).';
COMMENT ON COLUMN game_moves.move_number IS 'Порядковый номер полухода в партии.';
COMMENT ON COLUMN game_moves.player_id IS 'ID игрока, совершившего ход (FK к players).';
COMMENT ON COLUMN game_moves.move_notation IS 'Нотация хода в понятном для человека формате.';
COMMENT ON COLUMN game_moves.is_capture IS 'Флаг (Y/N), был ли ход взятием.';
COMMENT ON COLUMN game_moves.move_timestamp IS 'Точное время совершения хода.';


-- -----------------------------------------------------------------------------
-- AUDIT_LOG: Журнал событий
-- Для записи важных неигровых событий (ошибки валидации, таймауты и т.д.)
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
    log_id          NUMBER(18) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    log_timestamp   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    username        VARCHAR2(128),
    game_id         NUMBER(12),
    event_type      VARCHAR2(50) NOT NULL,
    event_details   VARCHAR2(1000)
);

COMMENT ON TABLE audit_log IS 'Журнал аудита для значимых событий и ошибок.';
COMMENT ON COLUMN audit_log.event_type IS 'Тип события (e.g., GAME_CREATED, INVALID_MOVE, SESSION_TIMEOUT).';
COMMENT ON COLUMN audit_log.event_details IS 'Подробности события.';


-- =============================================================================
-- 2. КОНСТРЕЙНТЫ (PK, FK, UK, CHECK)
-- =============================================================================

-- Primary Keys
ALTER TABLE players ADD CONSTRAINT pk_players PRIMARY KEY (player_id);
ALTER TABLE game_rules ADD CONSTRAINT pk_game_rules PRIMARY KEY (rule_id);
ALTER TABLE games ADD CONSTRAINT pk_games PRIMARY KEY (game_id);
ALTER TABLE game_moves ADD CONSTRAINT pk_game_moves PRIMARY KEY (move_id);
ALTER TABLE audit_log ADD CONSTRAINT pk_audit_log PRIMARY KEY (log_id);
-- Unique Keys
ALTER TABLE players ADD CONSTRAINT uk_players_username UNIQUE (username);
ALTER TABLE game_rules ADD CONSTRAINT uk_game_rules_name UNIQUE (rule_name);
ALTER TABLE game_moves ADD CONSTRAINT uk_game_moves_game_move UNIQUE (game_id, move_number);

-- Foreign Keys
ALTER TABLE games ADD CONSTRAINT fk_games_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id);
ALTER TABLE games ADD CONSTRAINT fk_games_player_white FOREIGN KEY (player_white_id) REFERENCES players(player_id);
ALTER TABLE games ADD CONSTRAINT fk_games_player_black FOREIGN KEY (player_black_id) REFERENCES players(player_id);
ALTER TABLE games ADD CONSTRAINT fk_games_winner FOREIGN KEY (winner_player_id) REFERENCES players(player_id);

ALTER TABLE game_moves ADD CONSTRAINT fk_game_moves_game FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE;
ALTER TABLE game_moves ADD CONSTRAINT fk_game_moves_player FOREIGN KEY (player_id) REFERENCES players(player_id);

-- Check Constraints
ALTER TABLE games ADD CONSTRAINT chk_games_status CHECK (status IN ('ACTIVE', 'WHITE_WIN', 'BLACK_WIN', 'DRAW', 'TIMEOUT', 'ABORTED'));
ALTER TABLE games ADD CONSTRAINT chk_games_turn CHECK (current_turn IN ('W', 'B'));
ALTER TABLE game_moves ADD CONSTRAINT chk_game_moves_capture CHECK (is_capture IN ('Y', 'N'));
ALTER TABLE game_rules ADD CONSTRAINT chk_game_rules_pos_rep CHECK (enable_pos_repetition_draw IN ('Y', 'N'));


-- =============================================================================
-- 3. ИНДЕКСЫ
-- Для ускорения частых запросов
-- =============================================================================

CREATE INDEX idx_games_status ON games(status);
CREATE INDEX idx_games_players ON games(player_white_id, player_black_id);
CREATE INDEX idx_game_moves_game_id ON game_moves(game_id);


-- =============================================================================
-- 4. НАЧАЛЬНЫЕ ДАННЫЕ (SEED DATA)
-- Заполняем справочник правил
-- =============================================================================

INSERT INTO game_rules (rule_id, rule_name, board_size, draw_moves_limit, enable_pos_repetition_draw)
VALUES (1, 'Русские шашки 8x8', 8, 30, 'Y');

INSERT INTO game_rules (rule_id, rule_name, board_size, draw_moves_limit, enable_pos_repetition_draw)
VALUES (2, 'Международные шашки 10x10', 10, 50, 'Y');

COMMIT;

PROMPT Schema for "Checkers on Oracle" has been created successfully.