-- 1. PLAYERS
CREATE TABLE players (
    player_id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR2(30) NOT NULL,
    created_at        DATE DEFAULT SYSDATE NOT NULL,
    last_activity_at  DATE,
    CONSTRAINT pk_players PRIMARY KEY (player_id),
    CONSTRAINT uk_players_username UNIQUE (username)
);