CREATE TABLE seasons (
    season_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    season_name VARCHAR2(100) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    CONSTRAINT pk_seasons PRIMARY KEY (season_id)
);