CREATE TABLE player_ratings (
    player_rating_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id        INT NOT NULL,
    rule_id          INT NOT NULL,
    season_id        INT NOT NULL,
    rating           INT DEFAULT 500 NOT NULL,
    CONSTRAINT pk_player_ratings PRIMARY KEY (player_rating_id),
    CONSTRAINT fk_ratings_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_ratings_season FOREIGN KEY (season_id) REFERENCES seasons(season_id)
);
COMMENT ON TABLE player_ratings IS 'Рейтинги и статистика игроков в разрезе правил и сезонов.';