CREATE TABLE matches (
    match_id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id            INT NOT NULL,
    games_to_win       INT NOT NULL,
    status             CHAR(1) DEFAULT 'O' NOT NULL, -- O: Open/Challenged, A: Active, C: Completed
    winner_player_id   INT,
    CONSTRAINT pk_matches PRIMARY KEY (match_id),
    CONSTRAINT fk_matches_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_matches_winner FOREIGN KEY (winner_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_matches_status CHECK (status IN ('O', 'A', 'C')),
    CONSTRAINT chk_matches_games_to_win CHECK (games_to_win > 0)
);
COMMENT ON TABLE matches IS 'Серии игр (матчи), состоящие из нескольких партий.';