CREATE TABLE puzzles (
    puzzle_id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    board_position       VARCHAR2(100) NOT NULL,
    rule_id              INT DEFAULT 1 NOT NULL,
    turn_to_move         CHAR(1) DEFAULT 'W' NOT NULL,
    moves_to_solve       INT DEFAULT NULL,
    difficulty_level     CHAR(1) DEFAULT 'E' NOT NULL,
    created_by_player_id INT,
    end_board_state      VARCHAR2(100) DEFAULT NULL,
    solution             VARCHAR2(1000), 
    CONSTRAINT pk_puzzles PRIMARY KEY (puzzle_id),
    CONSTRAINT fk_puzzles_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_puzzles_player FOREIGN KEY (created_by_player_id) REFERENCES players(player_id),
    CONSTRAINT chk_puzzles_turn CHECK (turn_to_move IN ('W', 'B'))
);