-- 7. GAMES
CREATE TABLE games (
    game_id                  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id                 INT,
    rule_id                  INT DEFAULT 1 NOT NULL,
    player_white_id          INT,
    player_black_id          INT,
    
    creator_player_color     CHAR(1) NOT NULL, 
    winner_player_color      CHAR(1),         
    draw_offered_by_color    CHAR(1),         
    
    status                   CHAR(1) NOT NULL, 
    current_turn             CHAR(1) DEFAULT 'W' NOT NULL,
    
    start_time               DATE DEFAULT SYSDATE NOT NULL,
    end_time                 DATE,
    time_limit_move_sec      INT,
    time_limit_game_sec      INT,
    ai_difficulty            CHAR(1),
    
    draw_offer_status        CHAR(1), 
    draw_offered_at          DATE,
    enable_pos_repetition_draw CHAR(1) DEFAULT 'N' NOT NULL,
    draw_moves_limit         INT,

    puzzle_id                INT,       
    is_daily_puzzle          CHAR(1) DEFAULT 'N' NOT NULL, 
    puzzle_status            CHAR(1),   

    CONSTRAINT pk_games PRIMARY KEY (game_id),
    CONSTRAINT fk_games_match FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_rule FOREIGN KEY (rule_id) REFERENCES game_rules(rule_id),
    CONSTRAINT fk_games_player_white FOREIGN KEY (player_white_id) REFERENCES players(player_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_player_black FOREIGN KEY (player_black_id) REFERENCES players(player_id) ON DELETE SET NULL,
    CONSTRAINT fk_games_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(puzzle_id) ON DELETE SET NULL, 
    
    CONSTRAINT chk_games_creator_color CHECK (creator_player_color IN ('W', 'B')),
    CONSTRAINT chk_games_winner_color CHECK (winner_player_color IN ('W', 'B') OR winner_player_color IS NULL),
    
    CONSTRAINT chk_games_status CHECK (status IN ('O', 'C', 'A', 'V', 'D', 'T', 'R')),
    CONSTRAINT chk_games_turn CHECK (current_turn IN ('W', 'B')),
    CONSTRAINT chk_ai_difficulty CHECK (ai_difficulty IN ('E', 'M', 'H') OR ai_difficulty IS NULL),
    
    CONSTRAINT chk_games_draw_status CHECK (draw_offer_status IN ('O', 'S', 'D')),
    CONSTRAINT chk_games_draw_offer_logic CHECK (
        (draw_offer_status IS NULL AND draw_offered_by_color IS NULL AND draw_offered_at IS NULL) OR
        (draw_offer_status IS NOT NULL AND draw_offered_by_color IS NOT NULL AND draw_offered_at IS NOT NULL)
    ),
    CONSTRAINT chk_game_rules_pos_rep CHECK (enable_pos_repetition_draw IN ('Y', 'N')),
    CONSTRAINT chk_game_draw_moves_limit CHECK (draw_moves_limit IS NULL OR draw_moves_limit > 0),
    
    CONSTRAINT chk_games_is_daily_puzzle CHECK (is_daily_puzzle IN ('Y', 'N')),
    CONSTRAINT chk_games_puzzle_status CHECK (puzzle_status IN ('p', 's', 'f') OR puzzle_status IS NULL)
);
COMMENT ON TABLE games IS 'Игровые партии, а также попытки решения задач (pve games).';