CREATE TABLE daily_puzzles (
    daily_puzzle_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    puzzle_date DATE NOT NULL,
    puzzle_id   INT NOT NULL,
    CONSTRAINT pk_daily_puzzles PRIMARY KEY (daily_puzzle_id),
    CONSTRAINT fk_daily_pzzles_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(puzzle_id)
);

