-- 11. SPECTATORS
CREATE TABLE spectators (
    spectator_session_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id            INT NOT NULL,
    game_id              INT NOT NULL,
    joined_at            DATE DEFAULT SYSDATE NOT NULL,
    left_at              DATE,
    CONSTRAINT pk_spectators PRIMARY KEY (spectator_session_id),
    CONSTRAINT fk_spectators_player FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
    CONSTRAINT fk_spectators_game FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);
COMMENT ON TABLE spectators IS 'Игроки, наблюдающие за активными партиями.';